### ISSUE TITLE
dplyr does not take constants from environment in db situations

### ISSUE THREAD

**Issue by JohnMount** [tidyverse/dplyr#3148]
`dplyr` does not take constants from environment in db situations (tested on both `SQLite` and `Sparklyr`).  

Notice below we can compare a column to the numeric constant `small` for in-memory `data.frame` data, but we can not do the same on database sources (tested on both `SQLite` and `Sparklyr`).  Adding an extra "`!!`" seems to work around the issue.

``` r
suppressPackageStartupMessages(library("dplyr"))
packageVersion("dplyr")
#> [1] '0.7.4'
suppressPackageStartupMessages(library("sparklyr"))
packageVersion("sparklyr")
#> [1] '0.6.3'

d <- data.frame(x = 1:2)
small <- 1

# Local example

# works
d %>% summarize(x_big_rate = mean(ifelse( x > small, 1, 0)))
#>   x_big_rate
#> 1        0.5


# SQLite example

my_db <- dplyr::src_sqlite(":memory:", create = TRUE)
# or can connect with:
# my_db <- DBI::dbConnect(RSQLite::SQLite(), ":memory:")
# RSQLite::initExtension(my_db) # needed for many summary fns.

dSQLite <- copy_to(my_db, d, 'dSQLite')

# fails
dSQLite %>% summarize(x_big_rate = mean(ifelse( x > small, 1, 0)))
#> Error in rsqlite_send_query(conn@ptr, statement): no such column: small

# works
dSQLite %>% summarize(x_big_rate = mean(ifelse( x > !!small, 1, 0)))
#> # Source:   lazy query [?? x 1]
#> # Database: sqlite 3.19.3 [:memory:]
#>   x_big_rate
#>        <dbl>
#> 1        0.5


# Spark example

sc <- sparklyr::spark_connect(version='2.0.2', 
                              master = "local")
dSpark <- copy_to(sc, d, 'dSpark')

# fails
dSpark %>% summarize(x_big_rate = mean(ifelse( x > small, 1, 0)))
#> Error: org.apache.spark.sql.AnalysisException: cannot resolve '`small`' given input columns: [x]; line 1 pos 28;
#> 'GlobalLimit 10
#> +- 'LocalLimit 10
#>    +- 'Project ['AVG(CASE WHEN (x#8 > 'small) THEN 1.0 ELSE 0.0 END) AS x_big_rate#53]
#>       +- SubqueryAlias dspark
#>          +- Relation[x#8] csv
#> 
#>  at org.apache.spark.sql.catalyst.analysis.package$AnalysisErrorAt.failAnalysis(package.scala:42)
#>  at org.apache.spark.sql.catalyst.analysis.CheckAnalysis$$anonfun$checkAnalysis$1$$anonfun$apply$2.applyOrElse(CheckAnalysis.scala:77)
#>  at org.apache.spark.sql.catalyst.analysis.CheckAnalysis$$anonfun$checkAnalysis$1$$anonfun$apply$2.applyOrElse(CheckAnalysis.scala:74)
#>  at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$transformUp$1.apply(TreeNode.scala:308)
#>  at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$transformUp$1.apply(TreeNode.scala:308)
#>  at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(TreeNode.scala:69)
#>  at org.apache.spark.sql.catalyst.trees.TreeNode.transformUp(TreeNode.scala:307)
#>  at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$4.apply(TreeNode.scala:305)
#>  at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$4.apply(TreeNode.scala:305)
#>  at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$5.apply(TreeNode.scala:328)
#>  at org.apache.spark.sql.catalyst.trees.TreeNode.mapProductIterator(TreeNode.scala:186)
#>  at org.apache.spark.sql.catalyst.trees.TreeNode.transformChildren(TreeNode.scala:326)
#>  at org.apache.spark.sql.catalyst.trees.TreeNode.transformUp(TreeNode.scala:305)
#>  at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$4.apply(TreeNode.scala:305)
#>  at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$4.apply(TreeNode.scala:305)
#>  at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$5$$anonfun$apply$11.apply(TreeNode.scala:365)
#>  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
#>  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
#>  at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
#>  at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
#>  at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
#>  at scala.collection.AbstractTraversable.map(Traversable.scala:104)
#>  at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$5.apply(TreeNode.scala:355)
#>  at org.apache.spark.sql.catalyst.trees.TreeNode.mapProductIterator(TreeNode.scala:186)
#>  at org.apache.spark.sql.catalyst.trees.TreeNode.transformChildren(TreeNode.scala:326)
#>  at org.apache.spark.sql.catalyst.trees.TreeNode.transformUp(TreeNode.scala:305)
#>  at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$4.apply(TreeNode.scala:305)
#>  at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$4.apply(TreeNode.scala:305)
#>  at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$5$$anonfun$apply$11.apply(TreeNode.scala:357)
#>  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
#>  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
#>  at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
#>  at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
#>  at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
#>  at scala.collection.AbstractTraversable.map(Traversable.scala:104)
#>  at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$5.apply(TreeNode.scala:355)
#>  at org.apache.spark.sql.catalyst.trees.TreeNode.mapProductIterator(TreeNode.scala:186)
#>  at org.apache.spark.sql.catalyst.trees.TreeNode.transformChildren(TreeNode.scala:326)
#>  at org.apache.spark.sql.catalyst.trees.TreeNode.transformUp(TreeNode.scala:305)
#>  at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$4.apply(TreeNode.scala:305)
#>  at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$4.apply(TreeNode.scala:305)
#>  at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$5.apply(TreeNode.scala:328)
#>  at org.apache.spark.sql.catalyst.trees.TreeNode.mapProductIterator(TreeNode.scala:186)
#>  at org.apache.spark.sql.catalyst.trees.TreeNode.transformChildren(TreeNode.scala:326)
#>  at org.apache.spark.sql.catalyst.trees.TreeNode.transformUp(TreeNode.scala:305)
#>  at org.apache.spark.sql.catalyst.plans.QueryPlan.transformExpressionUp$1(QueryPlan.scala:269)
#>  at org.apache.spark.sql.catalyst.plans.QueryPlan.org$apache$spark$sql$catalyst$plans$QueryPlan$$recursiveTransform$2(QueryPlan.scala:279)
#>  at org.apache.spark.sql.catalyst.plans.QueryPlan$$anonfun$org$apache$spark$sql$catalyst$plans$QueryPlan$$recursiveTransform$2$1.apply(QueryPlan.scala:283)
#>  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
#>  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
#>  at scala.collection.immutable.List.foreach(List.scala:381)
#>  at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
#>  at scala.collection.immutable.List.map(List.scala:285)
#>  at org.apache.spark.sql.catalyst.plans.QueryPlan.org$apache$spark$sql$catalyst$plans$QueryPlan$$recursiveTransform$2(QueryPlan.scala:283)
#>  at org.apache.spark.sql.catalyst.plans.QueryPlan$$anonfun$8.apply(QueryPlan.scala:288)
#>  at org.apache.spark.sql.catalyst.trees.TreeNode.mapProductIterator(TreeNode.scala:186)
#>  at org.apache.spark.sql.catalyst.plans.QueryPlan.transformExpressionsUp(QueryPlan.scala:288)
#>  at org.apache.spark.sql.catalyst.analysis.CheckAnalysis$$anonfun$checkAnalysis$1.apply(CheckAnalysis.scala:74)
#>  at org.apache.spark.sql.catalyst.analysis.CheckAnalysis$$anonfun$checkAnalysis$1.apply(CheckAnalysis.scala:67)
#>  at org.apache.spark.sql.catalyst.trees.TreeNode.foreachUp(TreeNode.scala:126)
#>  at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$foreachUp$1.apply(TreeNode.scala:125)
#>  at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$foreachUp$1.apply(TreeNode.scala:125)
#>  at scala.collection.immutable.List.foreach(List.scala:381)
#>  at org.apache.spark.sql.catalyst.trees.TreeNode.foreachUp(TreeNode.scala:125)
#>  at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$foreachUp$1.apply(TreeNode.scala:125)
#>  at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$foreachUp$1.apply(TreeNode.scala:125)
#>  at scala.collection.immutable.List.foreach(List.scala:381)
#>  at org.apache.spark.sql.catalyst.trees.TreeNode.foreachUp(TreeNode.scala:125)
#>  at org.apache.spark.sql.catalyst.analysis.CheckAnalysis$class.checkAnalysis(CheckAnalysis.scala:67)
#>  at org.apache.spark.sql.catalyst.analysis.Analyzer.checkAnalysis(Analyzer.scala:58)
#>  at org.apache.spark.sql.execution.QueryExecution.assertAnalyzed(QueryExecution.scala:49)
#>  at org.apache.spark.sql.Dataset$.ofRows(Dataset.scala:64)
#>  at org.apache.spark.sql.SparkSession.sql(SparkSession.scala:582)
#>  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
#>  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
#>  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
#>  at java.lang.reflect.Method.invoke(Method.java:497)
#>  at sparklyr.Invoke$.invoke(invoke.scala:102)
#>  at sparklyr.StreamHandler$.handleMethodCall(stream.scala:97)
#>  at sparklyr.StreamHandler$.read(stream.scala:62)
#>  at sparklyr.BackendHandler.channelRead0(handler.scala:52)
#>  at sparklyr.BackendHandler.channelRead0(handler.scala:14)
#>  at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
#>  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
#>  at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
#>  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
#>  at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:244)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
#>  at io.netty.channel.AbstractChannelHandlerContext.fireCha

# works
dSpark %>% summarize(x_big_rate = mean(ifelse( x > !!small, 1, 0)))
#> # Source:   lazy query [?? x 1]
#> # Database: spark_connection
#>   x_big_rate
#>        <dbl>
#> 1        0.5

spark_disconnect(sc)
```

**Comment by JohnMount** [comment]
Another example (also showing some irregularity in notation):

``` r
suppressPackageStartupMessages(library("dplyr"))
packageVersion("dplyr")
#> [1] '0.7.4'

genderTarget = 'male'

starwars %>% 
  summarize(fracMale = mean(ifelse(gender == genderTarget, 1, 0), 
                            na.rm = TRUE))
#> # A tibble: 1 x 1
#>    fracMale
#>       <dbl>
#> 1 0.7380952

my_db <- dplyr::src_sqlite(":memory:", create = TRUE)
# or can connect with:
# my_db <- DBI::dbConnect(RSQLite::SQLite(), ":memory:")
# RSQLite::initExtension(my_db) # needed for many summary fns.
starwars_db <- copy_to(my_db, 
                       select(starwars, -vehicles, -starships, -films), 
                       'starwars_db')

# works
starwars_db %>% transmute(genderTarget = genderTarget)
#> # Source:   lazy query [?? x 1]
#> # Database: sqlite 3.19.3 [:memory:]
#>    genderTarget
#>           <chr>
#>  1         male
#>  2         male
#>  3         male
#>  4         male
#>  5         male
#>  6         male
#>  7         male
#>  8         male
#>  9         male
#> 10         male
#> # ... with more rows

# fails
starwars_db %>% 
  summarize(fracMale = mean(ifelse(gender == genderTarget, 1, 0), 
                            na.rm = TRUE))
#> na.rm not needed in SQL: NULL are always droppedFALSE
#> Error in rsqlite_send_query(conn@ptr, statement): no such column: genderTarget

# fails
starwars_db %>% 
  summarize(fracMale = mean(if_else(gender == genderTarget, 1, 0), 
                            na.rm = TRUE))
#> na.rm not needed in SQL: NULL are always droppedFALSE
#> Error in rsqlite_send_query(conn@ptr, statement): no such column: genderTarget

# fix: use "!!" to force bind target to environment
starwars_db %>% 
  summarize(fracMale = mean(ifelse(gender == !!genderTarget, 1, 0), 
                            na.rm = TRUE))
#> na.rm not needed in SQL: NULL are always droppedFALSE
#> # Source:   lazy query [?? x 1]
#> # Database: sqlite 3.19.3 [:memory:]
#>    fracMale
#>       <dbl>
#> 1 0.7126437
```

**Comment by hadley** [comment]
Minimal reprex for first issue:

``` r
library(dplyr, warn.conflicts = FALSE)
library(dbplyr, warn.conflicts = FALSE)

db <- memdb_frame(g = c("a", "b"))
db %>% summarise(x = mean(ifelse(g == "a", 10, 20)))
#> # Source: lazy query [?? x 1]
#> # Database: sqlite 3.19.3 [:memory:]
#>       x
#>   <dbl>
#> 1  15.0

val <- "a"
db %>% summarise(x = mean(ifelse(g == val, 10, 20)))
#> Error in rsqlite_send_query(conn@ptr, statement): no such column: val
```

Can you please create a minimal reprex for the second issue (incorrect value) and open a separate issue? I suspect it's due to slightly different semantics for NULLs in databases.

**Comment by JohnMount** [comment]
Value issue entered as https://github.com/tidyverse/dplyr/issues/3157 .
